WITH tbl1 as (
SELECT
CLIENT_ID,
FULLSENIORITY_YEAR_CNT as stage,
STRFTIME('%Y', 'now')-STRFTIME('%Y', BIRTH_DT) as age,
CASE
WHEN FULLSENIORITY_YEAR_CNT LIKE 0 THEN 'N/A'
ELSE
ROUND(FULLSENIORITY_YEAR_CNT*100/(STRFTIME('%Y', 'now')-STRFTIME('%Y', BIRTH_DT)), 0)
END as ratio
FROM DIM_CLIENT)

SELECT CLIENT_ID, ratio
FROM tbl1
